---
  - name: clickhouse 
    src: git@github.com:davlyatov-ts/ansible-clickhouse.git
    scm: git
    version: "1.11.0"
  - name: lighthouse
    src: git@github.com:davlyatov-ts/lighthouse-role.git
    scm: git
    version: "1.0.0"
  - name: vector
    src: git@github.com:davlyatov-ts/vector-role.git
    scm: git
    version: "1.0.0"   
